"""Claude Code CLI agent (Option 1: CLI tool with a subscription auth token).

Architecturally identical to :class:`CodexAgent` — Django POSTs a chat request
to a containerised FastAPI gateway that spawns the CLI subprocess and streams
SSE back, and the per-request MCP tool filter is registered the same way. Only
two things differ, so this subclass overrides just those:

* **Service URL resolution** — routes to the Claude gateway (its own
  ``AgentConfiguration.service_url`` → ``claude_service_url`` system config →
  ``CLAUDE_SERVICE_URL`` env var) so it never accidentally hits the Codex
  container.
* **Credential** — Claude Code authenticates with a long-lived OAuth token
  (generated by ``claude setup-token`` on a machine with a Claude Pro/Max
  subscription). It is stored encrypted in ``_auth_token`` and forwarded to the
  gateway, which injects it as the ``CLAUDE_CODE_OAUTH_TOKEN`` env var for the
  subprocess. The credential is shorter-lived in shape than Codex's auth.json
  but plays the same role, so the parent's ``_apply_credentials`` (which sends
  ``payload["auth_token"]``) is reused unchanged.

Everything else — the SSE parsing, the ``\\x00TOOL:`` / ``\\x00RESPONSE:`` /
``\\x00THINKING:`` framing, MCP filter registration/clearing, model override,
history flattening, cancellation — is inherited from :class:`CodexAgent`.
"""

from __future__ import annotations

import os
from typing import TYPE_CHECKING

from .codex import CodexAgent

if TYPE_CHECKING:
    from ..models import AgentConfiguration


class ClaudeCodeAgent(CodexAgent):
    """Codex-style CLI agent that delegates to the Claude Code gateway."""

    def __init__(self, config: AgentConfiguration | None = None) -> None:
        self._config = config
        self._system_prompt = config.system_prompt if config else ""
        self._auth_token = config.get_auth_token() if config else ""

        # Resolve the service URL with a Claude-specific fallback chain so this
        # agent never routes to the Codex container by accident.
        config_service_url = (getattr(config, "service_url", "") or "") if config else ""

        from ..models import SystemConfiguration

        db_service_url = SystemConfiguration.get_value("claude_service_url", "") or ""
        self._service_url = (
            config_service_url or db_service_url or os.getenv("CLAUDE_SERVICE_URL", "")
        ).rstrip("/")
        if not self._service_url:
            raise RuntimeError(
                "ClaudeCodeAgent requires a service URL. Set this agent's service URL, "
                "the `claude_service_url` system configuration value, or the "
                "CLAUDE_SERVICE_URL environment variable."
            )
        self._http_response = None

    def get_name(self) -> str:
        return "Claude Code CLI (HTTP service)"


class ClaudeCodeApiAgent(ClaudeCodeAgent):
    """Claude Code CLI agent authenticated by an Anthropic API key instead of a
    subscription OAuth token.

    Reuses the entire ClaudeCodeAgent streaming/MCP-filter pipeline; only the
    credential and the service-URL resolution differ. The gateway injects the
    API key as the ``ANTHROPIC_API_KEY`` env var for the ``claude -p`` subprocess
    (no OAuth token). Mirrors :class:`engine.agents.codex.CodexApiAgent`.
    """

    def __init__(self, config: AgentConfiguration | None = None) -> None:
        self._config = config
        self._system_prompt = config.system_prompt if config else ""
        # API-key auth never uses the subscription OAuth token.
        self._auth_token = ""
        self._api_key = config.get_api_key() if config else ""

        # Resolve the service URL with a distinct fallback chain so this agent
        # never routes to the OAuth-token Claude container by accident.
        config_service_url = (getattr(config, "service_url", "") or "") if config else ""

        from ..models import SystemConfiguration

        db_service_url = SystemConfiguration.get_value("claude_api_service_url", "") or ""
        self._service_url = (
            config_service_url or db_service_url or os.getenv("CLAUDE_API_SERVICE_URL", "")
        ).rstrip("/")
        if not self._service_url:
            raise RuntimeError(
                "ClaudeCodeApiAgent requires a service URL. Set this agent's service URL, "
                "the `claude_api_service_url` system configuration value, or the "
                "CLAUDE_API_SERVICE_URL environment variable."
            )
        self._http_response = None

    def _apply_credentials(self, payload: dict[str, object]) -> None:
        if self._api_key:
            payload["api_key"] = self._api_key

    def get_name(self) -> str:
        return "Claude Code CLI (API key)"
