"""Dashboard, Chart, and ChartGenerationLog models."""

from django.contrib.auth.models import User
from django.db import models

from .connections import DatabaseConnection


class Dashboard(models.Model):
    """A collection of d3.js charts, generated by AI or created manually."""

    name = models.CharField(max_length=200, unique=True)
    description = models.TextField(blank=True)
    is_active = models.BooleanField(default=True)
    auto_refresh = models.BooleanField(
        default=False, help_text="Automatically refresh chart data on a schedule"
    )
    refresh_interval = models.CharField(
        max_length=10,
        blank=True,
        null=True,
        choices=[
            ("5", "Every 5 minutes"),
            ("15", "Every 15 minutes"),
            ("30", "Every 30 minutes"),
            ("60", "Every hour"),
            ("360", "Every 6 hours"),
            ("720", "Every 12 hours"),
            ("1440", "Every 24 hours"),
        ],
        help_text="How often to refresh chart data",
    )
    allowed_roles = models.ManyToManyField("Role", blank=True, related_name="allowed_dashboards")
    created_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True, related_name="created_dashboards"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Dashboard"
        verbose_name_plural = "Dashboards"
        ordering = ["name"]

    def __str__(self) -> str:
        return self.name


class Chart(models.Model):
    """A single d3.js chart within a dashboard."""

    CHART_TYPE_CHOICES = [
        ("bar", "Bar"),
        ("line", "Line"),
        ("scatter", "Scatter"),
        ("pie", "Pie"),
        ("area", "Area"),
        ("grouped_bar", "Grouped Bar"),
        ("stacked_bar", "Stacked Bar"),
        ("heatmap", "Heatmap"),
        ("custom", "Custom d3.js"),
    ]

    WIDTH_CHOICES = [
        (3, "Quarter"),
        (4, "Third"),
        (6, "Half"),
        (8, "Two-thirds"),
        (12, "Full"),
    ]

    dashboard = models.ForeignKey(Dashboard, on_delete=models.CASCADE, related_name="charts")
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    sql_query = models.TextField(help_text="Read-only SELECT query that produces chart data")
    chart_type = models.CharField(max_length=20, choices=CHART_TYPE_CHOICES, default="bar")
    chart_spec = models.JSONField(
        default=dict,
        blank=True,
        help_text="JSON chart specification: axes, colors, labels, options",
    )
    custom_d3_code = models.TextField(
        blank=True,
        default="",
        help_text=(
            "Raw d3.js code for the chart. Receives 'data' (array of row objects), "
            "'container' (DOM element), and 'd3' (the d3 library) as arguments."
        ),
    )
    database = models.ForeignKey(
        DatabaseConnection, on_delete=models.PROTECT, related_name="charts"
    )
    position = models.IntegerField(default=0, help_text="Ordering within dashboard grid")
    width = models.IntegerField(
        choices=WIDTH_CHOICES, default=6, help_text="CSS grid column span out of 12"
    )
    height = models.IntegerField(default=300, help_text="Chart height in pixels")
    is_active = models.BooleanField(default=True)
    cached_data = models.JSONField(
        default=dict, blank=True, help_text="Cached query results: {columns, rows, refreshed_at}"
    )
    last_refreshed_at = models.DateTimeField(null=True, blank=True)
    last_error = models.TextField(blank=True, default="")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Chart"
        verbose_name_plural = "Charts"
        ordering = ["position", "title"]

    def __str__(self) -> str:
        return f"{self.title} ({self.dashboard.name})"


class ChartGenerationLog(models.Model):
    """Audit log for AI dashboard/chart generation."""

    STATUS_CHOICES = [
        ("running", "Running"),
        ("success", "Success"),
        ("partial", "Partial"),
        ("failed", "Failed"),
    ]

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    agent = models.ForeignKey(
        "AgentConfiguration", on_delete=models.SET_NULL, null=True, blank=True
    )
    dashboard_name = models.CharField(max_length=200)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="running")
    started_at = models.DateTimeField(auto_now_add=True)
    completed_at = models.DateTimeField(null=True, blank=True)
    execution_time_ms = models.IntegerField(null=True, blank=True)
    source_databases = models.JSONField(default=list, blank=True)
    source_docs = models.JSONField(default=list, blank=True)
    charts_created = models.IntegerField(null=True, blank=True)
    errors = models.JSONField(default=list, blank=True)
    error_message = models.TextField(blank=True)
    prompt_used = models.TextField(blank=True)
    agent_output = models.TextField(blank=True)

    class Meta:
        ordering = ["-started_at"]
        verbose_name = "Chart Generation Log"
        verbose_name_plural = "Chart Generation Logs"

    def __str__(self) -> str:
        return f"{self.dashboard_name} — {self.status} ({self.started_at})"
