[mypy]
python_version = 3.11
strict = True
exclude = web/core/migrations/
mypy_path = web:stubs:.
plugins = mypy_django_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = tetherdust_web.settings
