python-interpreter = ".venv/bin/python"

project-includes = [
    "tdmcp/**/*.py",
    "tetherdust/**/*.py",
    "docker/**/*.py",
]

search-path = [
    "tetherdust/web",
    "tetherdust",
    ".",
]
