# Generated by Django 6.0.6 on 2026-06-16 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import engine.ids
import engine.models.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentConfiguration",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=engine.ids.generate_agt_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only one agent can be active at a time",
                        verbose_name="is active",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this agent configuration", max_length=100
                    ),
                ),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("codex", "Codex CLI"),
                            ("claude_code", "Claude Code CLI"),
                            ("codex_api", "Codex CLI (API key)"),
                            ("claude_code_api", "Claude Code CLI (API key)"),
                            ("openai_platform", "OpenAI Platform"),
                            ("claude_console", "Claude Console"),
                            ("openai_api", "OpenAI-compatible API (Custom)"),
                            ("ollama", "Local LLM with Ollama"),
                            ("openrouter", "OpenRouter (Gateway)"),
                        ],
                        default="codex",
                        max_length=50,
                        verbose_name="agent type",
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        blank=True,
                        help_text="System prompt / AGENTS.md content sent to the AI agent",
                        verbose_name="system prompt",
                    ),
                ),
                (
                    "auth_token",
                    engine.models.fields.EncryptedTextField(
                        blank=True,
                        db_column="auth_token",
                        default="",
                        help_text="Encrypted auth.json content from ChatGPT subscription sign-in (device-code login)",
                        verbose_name="auth token",
                    ),
                ),
                (
                    "api_key",
                    engine.models.fields.EncryptedTextField(
                        blank=True,
                        db_column="api_key",
                        default="",
                        help_text="Encrypted provider API key (e.g. OpenAI) for API-key CLI authentication",
                        verbose_name="API key",
                    ),
                ),
                (
                    "service_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Override for this agent's service URL (e.g. the Codex API gateway). Leave blank to fall back to the system-wide Codex Service URL or the CODEX_SERVICE_URL environment variable.",
                        verbose_name="service URL",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Backend-specific settings. For direct API agents: `model`, `base_url`, and optional `max_tokens`.",
                    ),
                ),
            ],
            options={
                "verbose_name": "agent configuration",
                "verbose_name_plural": "agent configurations",
                "ordering": ["-is_active", "name"],
                "constraints": [
                    models.UniqueConstraint(fields=("name",), name="uq_agentconfiguration_name")
                ],
            },
        ),
        migrations.CreateModel(
            name="ChartGenerationLog",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=engine.ids.generate_cgl_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="completed at"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("dashboard_name", models.CharField(max_length=200, verbose_name="dashboard name")),
                (
                    "execution_time_ms",
                    models.IntegerField(blank=True, null=True, verbose_name="execution time ms"),
                ),
                (
                    "source_databases",
                    models.JSONField(blank=True, default=list, verbose_name="source databases"),
                ),
                (
                    "source_docs",
                    models.JSONField(blank=True, default=list, verbose_name="source docs"),
                ),
                (
                    "charts_created",
                    models.IntegerField(blank=True, null=True, verbose_name="charts created"),
                ),
                ("errors", models.JSONField(blank=True, default=list)),
                ("error_message", models.TextField(blank=True, verbose_name="error message")),
                ("prompt_used", models.TextField(blank=True, verbose_name="prompt used")),
                ("agent_output", models.TextField(blank=True, verbose_name="agent output")),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="engine.agentconfiguration",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "chart generation log",
                "verbose_name_plural": "chart generation logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=engine.ids.generate_ses_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "chat session",
                "verbose_name_plural": "chat sessions",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=engine.ids.generate_msg_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "tools_used",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of MCP tool names used in this assistant message",
                        verbose_name="tools used",
                    ),
                ),
                (
                    "sources_used",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of {uri, name} dicts for MCP sources attached to this user message",
                        verbose_name="sources used",
                    ),
                ),
                (
                    "prompts_used",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of {name, display_name} dicts for prompts attached to this user message",
                        verbose_name="prompts used",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="engine.chatsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "chat message",
                "verbose_name_plural": "chat messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Codebase",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=engine.ids.generate_cb_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_synced_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="last synced at"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="is active")),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("syncing", "Syncing"),
                            ("ok", "Synced"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="sync status",
                    ),
                ),
                ("sync_error", models.TextField(blank=True, verbose_name="sync error")),
                (
                    "name",
                    models.CharField(
                        help_text="Unique identifier for this codebase", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Helps the AI agent understand what this repository contains",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("github", "GitHub")], default="github", max_length=20
                    ),
                ),
                (
                    "repo_url",
                    models.CharField(
                        help_text="e.g. https://github.com/owner/repo",
                        max_length=500,
                        verbose_name="repo URL",
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to use the repository's default branch",
                        max_length=255,
                    ),
                ),
                (
                    "subpath",
                    models.CharField(
                        blank=True,
                        help_text="Optional sub-directory to scope to, for monorepos (e.g. services/api)",
                        max_length=500,
                    ),
                ),
                (
                    "include_globs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Glob patterns to include, e.g. ["src/**", "*.py"]. Empty = everything (minus excludes).',
                        verbose_name="include globs",
                    ),
                ),
                (
                    "exclude_globs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Glob patterns to exclude. Empty = a sensible default set (node_modules, build output, binaries).",
                        verbose_name="exclude globs",
                    ),
                ),
                (
                    "access_token",
                    engine.models.fields.EncryptedCharField(
                        blank=True,
                        db_column="access_token",
                        help_text="Encrypted GitHub token. Leave blank for public repositories.",
                        max_length=500,
                        verbose_name="access token",
                    ),
                ),
                (
                    "default_branch",
                    models.CharField(
                        blank=True,
                        help_text="Resolved on sync",
                        max_length=255,
                        verbose_name="default branch",
                    ),
                ),
                (
                    "cached_tree",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Cached repository file tree (list of {path, type, size}), refreshed on sync.",
                        verbose_name="cached tree",
                    ),
                ),
            ],
            options={
                "verbose_name": "codebase",
                "verbose_name_plural": "codebases",
                "ordering": ["name"],
                "constraints": [models.UniqueConstraint(fields=("name",), name="uq_codebase_name")],
            },
        ),
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=engine.ids.generate_dsh_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True, verbose_name="is active")),
                (
                    "auto_refresh",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically refresh chart data on a schedule",
                        verbose_name="auto refresh",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "refresh_interval",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("5", "Every 5 minutes"),
                            ("15", "Every 15 minutes"),
                            ("30", "Every 30 minutes"),
                            ("60", "Every hour"),
                            ("360", "Every 6 hours"),
                            ("720", "Every 12 hours"),
                            ("1440", "Every 24 hours"),
                        ],
                        help_text="How often to refresh chart data",
                        max_length=10,
                        null=True,
                        verbose_name="refresh interval",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "dashboard",
                "verbose_name_plural": "dashboards",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DatabaseConnection",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=engine.ids.generate_db_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True, verbose_name="is active")),
                (
                    "name",
                    models.CharField(
                        help_text="Unique identifier for this connection", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Helps AI agent understand what data this database contains",
                    ),
                ),
                (
                    "engine",
                    models.CharField(
                        choices=[
                            ("postgresql", "PostgreSQL"),
                            ("mysql", "MySQL"),
                            ("mssql", "Microsoft SQL Server"),
                            ("oracle", "Oracle"),
                            ("sqlite", "SQLite"),
                            ("mariadb", "MariaDB"),
                            ("snowflake", "Snowflake"),
                            ("bigquery", "Google BigQuery"),
                            ("clickhouse", "ClickHouse"),
                        ],
                        default="postgresql",
                        max_length=50,
                    ),
                ),
                ("host", models.CharField(blank=True, max_length=255)),
                ("port", models.IntegerField(blank=True, null=True)),
                (
                    "database",
                    models.CharField(
                        blank=True,
                        help_text="Database name or file path for SQLite. Optional for engines with a default (e.g. ClickHouse uses 'default'), or when using a full connection_string.",
                        max_length=255,
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=255)),
                (
                    "password",
                    engine.models.fields.EncryptedCharField(
                        blank=True, db_column="password", max_length=500
                    ),
                ),
                (
                    "connection_string",
                    models.TextField(
                        blank=True,
                        help_text="Optional: Full SQLAlchemy URL (overrides above fields)",
                        verbose_name="connection string",
                    ),
                ),
                (
                    "extra_options",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional SQLAlchemy connect_args (e.g., SSL settings)",
                        verbose_name="extra options",
                    ),
                ),
                (
                    "read_only",
                    models.BooleanField(
                        default=True,
                        help_text="Strongly recommended. Runs every query in a read-only database session on PostgreSQL, MySQL/MariaDB, SQLite, Oracle, and ClickHouse. SQL Server, BigQuery, and Snowflake cannot enforce this at the session level — use a read-only database user / IAM role there. All engines are additionally checked by the SQL validator.",
                        verbose_name="read only",
                    ),
                ),
            ],
            options={
                "verbose_name": "database connection",
                "verbose_name_plural": "database connections",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["is_active", "name"], name="idx_dbconn_active_name")
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("name",), name="uq_databaseconnection_name")
                ],
            },
        ),
        migrations.CreateModel(
            name="Chart",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=engine.ids.generate_cht_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_refreshed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="last refreshed at"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="is active")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "sql_query",
                    models.TextField(
                        help_text="Read-only SELECT query that produces chart data",
                        verbose_name="SQL query",
                    ),
                ),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("bar", "Bar"),
                            ("line", "Line"),
                            ("scatter", "Scatter"),
                            ("pie", "Pie"),
                            ("area", "Area"),
                            ("grouped_bar", "Grouped Bar"),
                            ("stacked_bar", "Stacked Bar"),
                            ("heatmap", "Heatmap"),
                            ("custom", "Custom d3.js"),
                        ],
                        default="bar",
                        max_length=20,
                        verbose_name="chart type",
                    ),
                ),
                (
                    "chart_spec",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON chart specification: axes, colors, labels, options",
                        verbose_name="chart spec",
                    ),
                ),
                (
                    "custom_d3_code",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Raw d3.js code for the chart. Receives 'data' (array of row objects), 'container' (DOM element), and 'd3' (the d3 library) as arguments.",
                        verbose_name="custom d3 code",
                    ),
                ),
                (
                    "position",
                    models.IntegerField(default=0, help_text="Ordering within dashboard grid"),
                ),
                (
                    "width",
                    models.IntegerField(
                        choices=[
                            (3, "Quarter"),
                            (4, "Third"),
                            (6, "Half"),
                            (8, "Two-thirds"),
                            (12, "Full"),
                        ],
                        default=6,
                        help_text="CSS grid column span out of 12",
                    ),
                ),
                ("height", models.IntegerField(default=300, help_text="Chart height in pixels")),
                (
                    "cached_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Cached query results: {columns, rows, refreshed_at}",
                        verbose_name="cached data",
                    ),
                ),
                ("last_error", models.TextField(blank=True, default="", verbose_name="last error")),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charts",
                        to="engine.dashboard",
                    ),
                ),
                (
                    "database",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charts",
                        to="engine.databaseconnection",
                    ),
                ),
            ],
            options={
                "verbose_name": "chart",
                "verbose_name_plural": "charts",
                "ordering": ["position", "title"],
            },
        ),
        migrations.CreateModel(
            name="DocGenerationLog",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=engine.ids.generate_dgl_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="completed at"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("destination", models.CharField(max_length=500)),
                ("filename", models.CharField(blank=True, max_length=255)),
                ("doc_type", models.CharField(max_length=50, verbose_name="doc type")),
                (
                    "is_library",
                    models.BooleanField(
                        default=False,
                        help_text="True when this run generated a multi-file documentation library (a folder tree) rather than a single file.",
                        verbose_name="is library",
                    ),
                ),
                (
                    "execution_time_ms",
                    models.IntegerField(blank=True, null=True, verbose_name="execution time ms"),
                ),
                (
                    "source_databases",
                    models.JSONField(blank=True, default=list, verbose_name="source databases"),
                ),
                (
                    "source_docs",
                    models.JSONField(blank=True, default=list, verbose_name="source docs"),
                ),
                ("errors", models.JSONField(blank=True, default=list)),
                ("error_message", models.TextField(blank=True, verbose_name="error message")),
                ("file_size", models.IntegerField(blank=True, null=True, verbose_name="file size")),
                ("prompt_used", models.TextField(blank=True, verbose_name="prompt used")),
                ("agent_output", models.TextField(blank=True, verbose_name="agent output")),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="engine.agentconfiguration",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "doc generation log",
                "verbose_name_plural": "doc generation logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentationSource",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=engine.ids.generate_doc_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True, verbose_name="is active")),
                (
                    "folder_name",
                    models.CharField(
                        help_text="Folder name inside the documentations/ directory",
                        max_length=255,
                        verbose_name="folder name",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("database", "Database"),
                            ("codebase", "Codebase"),
                            ("manual", "Manual"),
                            ("policy", "Policy"),
                            ("api", "API"),
                            ("report", "Report"),
                            ("ontology", "Ontology"),
                            ("runbook", "Runbook"),
                        ],
                        default="database",
                        help_text="The category of documentation this source contains",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Helps AI understand what this source contains"
                    ),
                ),
                (
                    "file_patterns",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Glob patterns for files, e.g. ["*.md"] or ["*.py", "*.sql"]. Leave empty for default (*.md).',
                        verbose_name="file patterns",
                    ),
                ),
            ],
            options={
                "verbose_name": "documentation source",
                "verbose_name_plural": "documentation sources",
                "ordering": ["folder_name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "folder_name"], name="idx_docsrc_active_folder"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("folder_name",), name="uq_documentationsource_folder"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MCPServerConfiguration",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=engine.ids.generate_mcp_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True, verbose_name="is active")),
                (
                    "is_builtin",
                    models.BooleanField(
                        default=False,
                        help_text="Built-in servers cannot be edited or deleted",
                        verbose_name="is builtin",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Display name for this MCP server", max_length=100),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="What this MCP server provides"),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        help_text="Full MCP endpoint URL, e.g. https://example.com/mcp (leave blank for the built-in server)",
                        max_length=500,
                        verbose_name="URL",
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        blank=True, help_text="Deprecated — use `url` instead", max_length=255
                    ),
                ),
                (
                    "port",
                    models.IntegerField(
                        blank=True, help_text="Deprecated — use `url` instead", null=True
                    ),
                ),
                (
                    "transport",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Local (built-in)"),
                            ("sse", "SSE"),
                            ("streamable-http", "Streamable HTTP"),
                        ],
                        default="",
                        help_text="Transport protocol (leave blank for the built-in server)",
                        max_length=20,
                    ),
                ),
                (
                    "auth_token",
                    engine.models.fields.EncryptedCharField(
                        blank=True,
                        db_column="auth_token",
                        help_text="Encrypted bearer token sent as Authorization: Bearer …",
                        max_length=500,
                        verbose_name="auth token",
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Extra HTTP headers sent to the MCP server, e.g. {"X-API-Key": "abc"}',
                    ),
                ),
                (
                    "command",
                    models.CharField(
                        blank=True,
                        help_text='Executable to run, e.g. "npx" or "uvx". Set this for local subprocess servers.',
                        max_length=500,
                    ),
                ),
                (
                    "args",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Arguments for the command, e.g. ["-y", "@notionhq/notion-mcp-server"]',
                    ),
                ),
                (
                    "command_env",
                    engine.models.fields.EncryptedJSONField(
                        blank=True,
                        db_column="command_env",
                        default=dict,
                        help_text="Encrypted JSON dict of environment variables passed to the subprocess.",
                        verbose_name="command env",
                    ),
                ),
            ],
            options={
                "verbose_name": "MCP server",
                "verbose_name_plural": "MCP servers",
                "ordering": ["-is_builtin", "name"],
                "constraints": [
                    models.UniqueConstraint(fields=("name",), name="uq_mcpserverconfiguration_name")
                ],
            },
        ),
        migrations.CreateModel(
            name="PromptConfiguration",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=engine.ids.generate_prm_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_enabled", models.BooleanField(default=True, verbose_name="is enabled")),
                (
                    "prompt_name",
                    models.CharField(
                        help_text="Internal prompt name (e.g., 'analyze_table')",
                        max_length=100,
                        verbose_name="prompt name",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name shown in autocomplete",
                        max_length=100,
                        verbose_name="display name",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        default="",
                        help_text="The prompt instructions. This text is prepended to the user's message as context for the AI agent.",
                    ),
                ),
                (
                    "mcp_server",
                    models.ForeignKey(
                        help_text="MCP server this prompt belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompts",
                        to="engine.mcpserverconfiguration",
                    ),
                ),
            ],
            options={
                "verbose_name": "prompt configuration",
                "verbose_name_plural": "prompt configurations",
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="QueryAuditLog",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=engine.ids.generate_qal_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=True)),
                ("query", models.TextField()),
                ("row_count", models.IntegerField(null=True, verbose_name="row count")),
                (
                    "execution_time_ms",
                    models.IntegerField(null=True, verbose_name="execution time ms"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="error message")),
                (
                    "database",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="engine.databaseconnection",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "query audit log",
                "verbose_name_plural": "query audit logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportDefinition",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=engine.ids.generate_rpt_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True, verbose_name="is active")),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "sql_query",
                    models.TextField(
                        help_text="Read-only SELECT or WITH query", verbose_name="SQL query"
                    ),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("interval", "Every N Minutes/Hours"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="schedule type",
                    ),
                ),
                (
                    "schedule_interval_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="Run every N minutes (for interval schedule)",
                        null=True,
                        verbose_name="schedule interval minutes",
                    ),
                ),
                (
                    "schedule_time",
                    models.TimeField(
                        blank=True,
                        help_text="Time of day for scheduled runs",
                        null=True,
                        verbose_name="schedule time",
                    ),
                ),
                (
                    "schedule_day_of_week",
                    models.IntegerField(
                        blank=True,
                        help_text="0=Monday .. 6=Sunday (for weekly)",
                        null=True,
                        verbose_name="schedule day of week",
                    ),
                ),
                (
                    "schedule_day_of_month",
                    models.IntegerField(
                        blank=True,
                        help_text="1-28 (for monthly)",
                        null=True,
                        verbose_name="schedule day of month",
                    ),
                ),
                (
                    "next_run_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Computed next execution time",
                        null=True,
                        verbose_name="next run at",
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("in_app", "In-App"),
                            ("email", "Email"),
                            ("slack", "Slack"),
                            ("teams", "Microsoft Teams"),
                        ],
                        default="in_app",
                        max_length=20,
                        verbose_name="delivery method",
                    ),
                ),
                (
                    "delivery_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Future: email addresses, webhook URLs",
                        verbose_name="delivery config",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "database",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="engine.databaseconnection",
                    ),
                ),
            ],
            options={
                "verbose_name": "report definition",
                "verbose_name_plural": "report definitions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReportExecution",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=engine.ids.generate_rex_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="completed at"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                (
                    "execution_time_ms",
                    models.IntegerField(blank=True, null=True, verbose_name="execution time ms"),
                ),
                ("row_count", models.IntegerField(blank=True, null=True, verbose_name="row count")),
                (
                    "result_file_path",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="result file path"
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="error message")),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="engine.reportdefinition",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "report execution",
                "verbose_name_plural": "report executions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=engine.ids.generate_rol_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="is active")),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "max_row_limit",
                    models.IntegerField(
                        default=100,
                        help_text="Maximum rows per query",
                        verbose_name="max row limit",
                    ),
                ),
                (
                    "can_manage_users",
                    models.BooleanField(default=False, verbose_name="can manage users"),
                ),
                (
                    "can_chat",
                    models.BooleanField(
                        default=True,
                        help_text="Allow users with this role to use the chat interface.",
                        verbose_name="can chat",
                    ),
                ),
                (
                    "can_view_tethers",
                    models.BooleanField(
                        default=True,
                        help_text="Allow users with this role to view Tethers.",
                        verbose_name="can view tethers",
                    ),
                ),
                (
                    "is_admin_role",
                    models.BooleanField(
                        default=False,
                        help_text="Admin roles bypass all access restrictions. Access control settings are ignored.",
                        verbose_name="is admin role",
                    ),
                ),
                (
                    "allowed_codebases",
                    models.ManyToManyField(blank=True, related_name="roles", to="engine.codebase"),
                ),
                (
                    "allowed_databases",
                    models.ManyToManyField(
                        blank=True, related_name="roles", to="engine.databaseconnection"
                    ),
                ),
                (
                    "allowed_doc_sources",
                    models.ManyToManyField(
                        blank=True, related_name="roles_docs", to="engine.documentationsource"
                    ),
                ),
                (
                    "allowed_mcp_servers",
                    models.ManyToManyField(
                        blank=True, related_name="roles", to="engine.mcpserverconfiguration"
                    ),
                ),
                (
                    "allowed_prompts",
                    models.ManyToManyField(
                        blank=True, related_name="roles", to="engine.promptconfiguration"
                    ),
                ),
            ],
            options={
                "verbose_name": "role",
                "verbose_name_plural": "roles",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="reportdefinition",
            name="allowed_roles",
            field=models.ManyToManyField(
                blank=True, related_name="allowed_reports", to="engine.role"
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="allowed_roles",
            field=models.ManyToManyField(
                blank=True, related_name="allowed_dashboards", to="engine.role"
            ),
        ),
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=engine.ids.generate_cfg_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("value", models.TextField()),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("boolean", "Boolean"),
                            ("json", "JSON"),
                        ],
                        default="string",
                        max_length=20,
                        verbose_name="value type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Explain what this setting does"),
                ),
            ],
            options={
                "verbose_name": "system configuration",
                "verbose_name_plural": "system configuration",
                "ordering": ["key"],
                "constraints": [
                    models.UniqueConstraint(fields=("key",), name="uq_systemconfiguration_key")
                ],
            },
        ),
        migrations.CreateModel(
            name="Tether",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=engine.ids.generate_tth_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True, verbose_name="is active")),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "allowed_roles",
                    models.ManyToManyField(
                        blank=True, related_name="allowed_tethers", to="engine.role"
                    ),
                ),
                (
                    "codebase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tethers",
                        to="engine.codebase",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tethers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "database_doc_source",
                    models.ForeignKey(
                        limit_choices_to={"doc_type": "database"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tethers_as_database",
                        to="engine.documentationsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "tether",
                "verbose_name_plural": "tethers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TetherVersion",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=engine.ids.generate_tvr_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="completed at"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("version_number", models.IntegerField(verbose_name="version number")),
                (
                    "execution_time_ms",
                    models.IntegerField(blank=True, null=True, verbose_name="execution time ms"),
                ),
                (
                    "graph_json",
                    models.JSONField(blank=True, default=dict, verbose_name="graph JSON"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="error message")),
                (
                    "agent_log_excerpt",
                    models.TextField(
                        blank=True,
                        help_text="Last ~4kB of Codex stream for debugging",
                        verbose_name="agent log excerpt",
                    ),
                ),
                ("prompt_used", models.TextField(blank=True, verbose_name="prompt used")),
                (
                    "tether",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="engine.tether",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "tether version",
                "verbose_name_plural": "tether versions",
                "ordering": ["-version_number"],
            },
        ),
        migrations.AddField(
            model_name="tether",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                help_text="Latest successful run; what the viewer renders.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="engine.tetherversion",
            ),
        ),
        migrations.CreateModel(
            name="ToolConfiguration",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=engine.ids.generate_tool_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_enabled", models.BooleanField(default=True, verbose_name="is enabled")),
                (
                    "tool_name",
                    models.CharField(
                        help_text="Internal tool name (e.g., 'search_docs')",
                        max_length=100,
                        verbose_name="tool name",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name", max_length=100, verbose_name="display name"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("querying", "Querying"),
                            ("docs", "Docs"),
                            ("charts", "Charts"),
                            ("codebases", "Codebases"),
                            ("tethers", "Tethers"),
                            ("reports", "Reports"),
                        ],
                        default="",
                        help_text="TetherDust feature this tool belongs to (groups tools in the management).",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="AI-facing description that guides when/how the tool is used"
                    ),
                ),
                (
                    "input_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='MCP tool input schema (JSON Schema). Example: {"type": "object", "properties": {"query": {"type": "string"}}, "required": ["query"]}',
                        verbose_name="input schema",
                    ),
                ),
                (
                    "source_code",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Python handler code. Must define an async function handle(arguments: dict) -> str that returns the tool result text.",
                        verbose_name="source code",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Tool-specific settings (e.g., max_results, timeout)",
                    ),
                ),
                (
                    "mcp_server",
                    models.ForeignKey(
                        help_text="MCP server this tool belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tools",
                        to="engine.mcpserverconfiguration",
                    ),
                ),
            ],
            options={
                "verbose_name": "tool configuration",
                "verbose_name_plural": "tool configurations",
                "ordering": ["category", "display_name"],
            },
        ),
        migrations.AddField(
            model_name="role",
            name="allowed_tools",
            field=models.ManyToManyField(
                blank=True, related_name="roles", to="engine.toolconfiguration"
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=engine.ids.generate_usp_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="engine.role",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user profile",
                "verbose_name_plural": "user profiles",
            },
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(fields=["user", "-updated_at"], name="idx_chatsession_user_recent"),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "created_at"], name="idx_chatmessage_session_time"
            ),
        ),
        migrations.AddIndex(
            model_name="chart",
            index=models.Index(fields=["dashboard", "is_active"], name="idx_chart_dash_active"),
        ),
        migrations.AddIndex(
            model_name="chart",
            index=models.Index(fields=["dashboard", "position"], name="idx_chart_dash_position"),
        ),
        migrations.AddConstraint(
            model_name="promptconfiguration",
            constraint=models.UniqueConstraint(
                fields=("prompt_name",), name="uq_promptconfiguration_prompt_name"
            ),
        ),
        migrations.AddIndex(
            model_name="queryauditlog",
            index=models.Index(fields=["-created_at"], name="idx_qal_recent"),
        ),
        migrations.AddIndex(
            model_name="queryauditlog",
            index=models.Index(fields=["success", "-created_at"], name="idx_qal_success_recent"),
        ),
        migrations.AddIndex(
            model_name="queryauditlog",
            index=models.Index(fields=["database", "-created_at"], name="idx_qal_db_recent"),
        ),
        migrations.AddIndex(
            model_name="reportexecution",
            index=models.Index(
                fields=["definition", "status", "-started_at"],
                name="idx_reportexecution_def_status",
            ),
        ),
        migrations.AddIndex(
            model_name="reportdefinition",
            index=models.Index(fields=["is_active", "name"], name="idx_reportdef_active_name"),
        ),
        migrations.AddConstraint(
            model_name="reportdefinition",
            constraint=models.UniqueConstraint(fields=("name",), name="uq_reportdefinition_name"),
        ),
        migrations.AddIndex(
            model_name="dashboard",
            index=models.Index(fields=["is_active", "name"], name="idx_dashboard_active_name"),
        ),
        migrations.AddConstraint(
            model_name="dashboard",
            constraint=models.UniqueConstraint(fields=("name",), name="uq_dashboard_name"),
        ),
        migrations.AddConstraint(
            model_name="tetherversion",
            constraint=models.UniqueConstraint(
                fields=("tether", "version_number"), name="uq_tetherversion_tether_version"
            ),
        ),
        migrations.AddIndex(
            model_name="tether",
            index=models.Index(fields=["is_active", "name"], name="idx_tether_active_name"),
        ),
        migrations.AddConstraint(
            model_name="toolconfiguration",
            constraint=models.UniqueConstraint(
                fields=("tool_name",), name="uq_toolconfiguration_tool_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(fields=("name",), name="uq_role_name"),
        ),
    ]
