# Generated by Django 6.0.6 on 2026-07-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0002_tether_codebase_doc_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codebase",
            name="provider",
            field=models.CharField(
                choices=[("github", "GitHub"), ("gitlab", "GitLab")],
                default="github",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="codebase",
            name="repo_url",
            field=models.CharField(
                help_text="e.g. https://github.com/owner/repo or https://gitlab.com/group/project",
                max_length=500,
                verbose_name="repo URL",
            ),
        ),
    ]
