# Generated by Django 6.0.6 on 2026-07-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0003_alter_codebase_provider_alter_codebase_repo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="codebase",
            name="local_root",
            field=models.CharField(
                blank=True,
                help_text="For local codebases: the folder name under sources/codebases/.",
                max_length=255,
                verbose_name="local root",
            ),
        ),
        migrations.AlterField(
            model_name="codebase",
            name="provider",
            field=models.CharField(
                choices=[("github", "GitHub"), ("gitlab", "GitLab"), ("local", "Local")],
                default="github",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="codebase",
            name="repo_url",
            field=models.CharField(
                blank=True,
                help_text="e.g. https://github.com/owner/repo or https://gitlab.com/group/project",
                max_length=500,
                verbose_name="repo URL",
            ),
        ),
    ]
