# Generated by Django 6.0.6 on 2026-07-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0004_codebase_local_root_alter_codebase_provider_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="databaseconnection",
            name="engine",
            field=models.CharField(
                choices=[
                    ("postgresql", "PostgreSQL"),
                    ("mysql", "MySQL"),
                    ("mssql", "Microsoft SQL Server"),
                    ("sqlite", "SQLite"),
                    ("mariadb", "MariaDB"),
                    ("clickhouse", "ClickHouse"),
                ],
                default="postgresql",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="databaseconnection",
            name="read_only",
            field=models.BooleanField(
                default=True,
                help_text="Strongly recommended. Runs every query in a read-only database session on PostgreSQL, MySQL/MariaDB, SQLite, and ClickHouse. SQL Server cannot enforce this at the session level — use a read-only database user there. All engines are additionally checked by the SQL validator.",
                verbose_name="read only",
            ),
        ),
    ]
