# Generated by Django 6.0.6 on 2026-07-16 08:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0005_remove_oracle_snowflake_bigquery"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="codebase",
            name="exclude_globs",
        ),
        migrations.RemoveField(
            model_name="codebase",
            name="include_globs",
        ),
    ]
