# Generated by Django 6.0.6 on 2026-07-16 09:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0006_remove_codebase_globs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="codebase",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="codebase",
            name="subpath",
        ),
    ]
