# Generated by Django 6.0.6 on 2026-07-20 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0007_remove_codebase_branch_subpath"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentationsource",
            name="file_patterns",
        ),
    ]
