# Generated by Django 6.0.6 on 2026-07-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0008_remove_documentationsource_file_patterns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentationsource",
            name="folder_name",
            field=models.CharField(
                help_text="Folder name inside the sources/docs/ directory",
                max_length=255,
                verbose_name="folder name",
            ),
        ),
    ]
