# Generated by Django 6.0.6 on 2026-07-28 18:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0009_alter_documentationsource_folder_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agentconfiguration",
            options={
                "ordering": ["created_at"],
                "verbose_name": "agent configuration",
                "verbose_name_plural": "agent configurations",
            },
        ),
    ]
