import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { apiErrorDetail } from "../../api/client";
import {
	type AdminDashboard,
	deleteDashboard,
	listDashboards,
} from "../../api/dashboards";

export function AdminDashboardsPage() {
	const queryClient = useQueryClient();
	const { data, isLoading, isError } = useQuery({
		queryKey: ["admin", "dashboards"],
		queryFn: listDashboards,
	});
	const remove = useMutation({
		mutationFn: deleteDashboard,
		onSuccess: () =>
			queryClient.invalidateQueries({ queryKey: ["admin", "dashboards"] }),
		onError: (err) => window.alert(apiErrorDetail(err, "Delete failed.")),
	});

	function onDelete(d: AdminDashboard) {
		if (window.confirm(`Delete dashboard "${d.name}" and all its charts?`)) {
			remove.mutate(d.id);
		}
	}

	const dashboards = data?.results ?? [];

	return (
		<div>
			<div className="page-header">
				<div>
					<h1>Dashboards</h1>
					<p>D3 chart dashboards — built manually or generated by AI</p>
				</div>
				<Link to="/admin/dashboards/add" className="btn btn-primary">
					+ Add Dashboard
				</Link>
			</div>

			<div className="card">
				{isLoading ? (
					<p className="text-sec">Loading…</p>
				) : isError ? (
					<p className="text-sec">Failed to load dashboards.</p>
				) : dashboards.length === 0 ? (
					<div className="empty-state">
						<div className="icon">
							<i className="fa-solid fa-chart-bar" />
						</div>
						<h3>No Dashboards</h3>
						<p className="text-sec">
							Create one manually or generate it with AI.
						</p>
						<Link to="/admin/dashboards/add" className="btn btn-primary mt-md">
							+ Add Dashboard
						</Link>
					</div>
				) : (
					<div className="table-wrap">
						<table>
							<thead>
								<tr>
									<th>Name</th>
									<th>Charts</th>
									<th>Status</th>
									<th>Actions</th>
								</tr>
							</thead>
							<tbody>
								{dashboards.map((d) => (
									<tr key={d.id}>
										<td>
											<strong>{d.name}</strong>
											{d.description && (
												<div className="text-sm text-sec truncate">
													{d.description}
												</div>
											)}
										</td>
										<td>{d.chart_count}</td>
										<td>
											{d.is_active ? (
												<span className="badge badge-success">ACTIVE</span>
											) : (
												<span className="badge badge-muted">INACTIVE</span>
											)}
										</td>
										<td>
											<div className="flex-gap">
												<Link
													to={`/admin/dashboards/${d.id}`}
													className="btn btn-ghost btn-sm"
												>
													<i className="fa-solid fa-chart-column" /> Charts
												</Link>
												<Link
													to={`/admin/dashboards/${d.id}/edit`}
													className="btn btn-ghost btn-sm"
												>
													<i className="fa-solid fa-pen" /> Edit
												</Link>
												<Link
													to={`/dashboards/${d.id}`}
													className="btn btn-ghost btn-sm"
												>
													<i className="fa-solid fa-eye" /> View
												</Link>
												<button
													type="button"
													className="btn btn-ghost btn-sm"
													style={{ color: "var(--danger)" }}
													onClick={() => onDelete(d)}
												>
													<i className="fa-solid fa-trash" /> Delete
												</button>
											</div>
										</td>
									</tr>
								))}
							</tbody>
						</table>
					</div>
				)}
			</div>
		</div>
	);
}
