import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { apiErrorDetail } from "../../api/client";
import { type AdminTether, deleteTether, listTethers } from "../../api/tethers";

function StatusBadge({ status }: { status: string | null }) {
	if (status === "success")
		return <span className="badge badge-success">READY</span>;
	if (status === "failed")
		return <span className="badge badge-error">FAILED</span>;
	if (status === "running")
		return <span className="badge badge-muted">RUNNING</span>;
	return <span className="badge badge-muted">—</span>;
}

export function AdminTethersPage() {
	const queryClient = useQueryClient();
	const { data, isLoading, isError } = useQuery({
		queryKey: ["admin", "tethers"],
		queryFn: listTethers,
	});

	const remove = useMutation({
		mutationFn: deleteTether,
		onSuccess: () =>
			queryClient.invalidateQueries({ queryKey: ["admin", "tethers"] }),
		onError: (err) => window.alert(apiErrorDetail(err, "Delete failed.")),
	});

	function onDelete(t: AdminTether) {
		if (window.confirm(`Delete tether "${t.name}" and all its versions?`))
			remove.mutate(t.id);
	}

	const tethers = data?.results ?? [];

	return (
		<div>
			<div className="page-header">
				<div>
					<h1>Tethers</h1>
					<p>Visual code ↔ database links, generated by the agent</p>
				</div>
				<Link to="/admin/tethers/new" className="btn btn-primary">
					+ Add Tether
				</Link>
			</div>

			<div className="card">
				{isLoading ? (
					<p className="text-sec">Loading…</p>
				) : isError ? (
					<p className="text-sec">Failed to load tethers.</p>
				) : tethers.length === 0 ? (
					<div className="empty-state">
						<div className="icon">
							<i className="fa-solid fa-diagram-project" />
						</div>
						<h3>No Tethers</h3>
						<p className="text-sec">
							Create one to map a codebase against a database.
						</p>
						<Link to="/admin/tethers/new" className="btn btn-primary mt-md">
							+ Add Tether
						</Link>
					</div>
				) : (
					<div className="table-wrap">
						<table>
							<thead>
								<tr>
									<th>Name</th>
									<th>Link</th>
									<th>Status</th>
									<th>Actions</th>
								</tr>
							</thead>
							<tbody>
								{tethers.map((t) => (
									<tr key={t.id}>
										<td>
											<strong>{t.name}</strong>
										</td>
										<td className="text-sm">
											{t.source_name} ↔ {t.database_name}
										</td>
										<td>
											<StatusBadge
												status={t.latest_version?.status ?? t.current_status}
											/>
										</td>
										<td>
											<div className="flex-gap">
												<Link
													to={`/admin/tethers/${t.id}`}
													className="btn btn-ghost btn-sm"
												>
													<i className="fa-solid fa-sliders" /> Manage
												</Link>
												<Link
													to={`/admin/tethers/${t.id}/edit`}
													className="btn btn-ghost btn-sm"
												>
													<i className="fa-solid fa-pen" /> Edit
												</Link>
												<Link
													to={`/tethers/${t.id}`}
													className="btn btn-ghost btn-sm"
												>
													<i className="fa-solid fa-eye" /> View
												</Link>
												<button
													type="button"
													className="btn btn-ghost btn-sm"
													style={{ color: "var(--danger)" }}
													onClick={() => onDelete(t)}
												>
													<i className="fa-solid fa-trash" /> Delete
												</button>
											</div>
										</td>
									</tr>
								))}
							</tbody>
						</table>
					</div>
				)}
			</div>
		</div>
	);
}
