"""Dashboard, Chart, and ChartGenerationLog models."""

from __future__ import annotations

from typing import TYPE_CHECKING, ClassVar

from django.contrib.auth.models import User
from django.db import models

from ..ids import generate_cgl_id, generate_cht_id, generate_dsh_id

if TYPE_CHECKING:
    from .auth import Role

from .connections import DatabaseConnection


class Dashboard(models.Model):
    """A collection of d3.js charts, generated by AI or created manually."""

    class Meta:
        verbose_name = "dashboard"
        verbose_name_plural = "dashboards"
        ordering = ["name"]
        indexes = [
            models.Index(fields=["is_active", "name"], name="idx_%(class)s_active_name"),
        ]
        constraints = [
            models.UniqueConstraint(fields=["name"], name="uq_%(class)s_name"),
        ]

    REFRESH_INTERVAL_CHOICES: ClassVar[list[tuple[str, str]]] = [
        ("5", "Every 5 minutes"),
        ("15", "Every 15 minutes"),
        ("30", "Every 30 minutes"),
        ("60", "Every hour"),
        ("360", "Every 6 hours"),
        ("720", "Every 12 hours"),
        ("1440", "Every 24 hours"),
    ]

    __prefix__: ClassVar[str] = "dsh"

    # Identifiers
    id = models.CharField(max_length=64, primary_key=True, default=generate_dsh_id, editable=False)

    # Time
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # State
    is_active = models.BooleanField(verbose_name="is active", default=True)
    auto_refresh = models.BooleanField(
        verbose_name="auto refresh",
        default=False,
        help_text="Automatically refresh chart data on a schedule",
    )

    # Domain
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    refresh_interval = models.CharField(
        verbose_name="refresh interval",
        max_length=10,
        blank=True,
        null=True,
        choices=REFRESH_INTERVAL_CHOICES,
        help_text="How often to refresh chart data",
    )

    # Relations
    allowed_roles: models.ManyToManyField[Role, Role] = models.ManyToManyField(
        "Role", blank=True, related_name="allowed_dashboards"
    )
    created_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True, related_name="created_dashboards"
    )

    def __str__(self) -> str:
        return self.name


class Chart(models.Model):
    """A single d3.js chart within a dashboard."""

    class Meta:
        verbose_name = "chart"
        verbose_name_plural = "charts"
        ordering = ["position", "title"]
        indexes = [
            models.Index(fields=["dashboard", "is_active"], name="idx_%(class)s_dash_active"),
            models.Index(fields=["dashboard", "position"], name="idx_%(class)s_dash_position"),
        ]

    CHART_TYPE_CHOICES: ClassVar[list[tuple[str, str]]] = [
        ("bar", "Bar"),
        ("line", "Line"),
        ("scatter", "Scatter"),
        ("pie", "Pie"),
        ("area", "Area"),
        ("grouped_bar", "Grouped Bar"),
        ("stacked_bar", "Stacked Bar"),
        ("heatmap", "Heatmap"),
        ("custom", "Custom d3.js"),
    ]

    WIDTH_CHOICES: ClassVar[list[tuple[int, str]]] = [
        (3, "Quarter"),
        (4, "Third"),
        (6, "Half"),
        (8, "Two-thirds"),
        (12, "Full"),
    ]

    __prefix__: ClassVar[str] = "cht"

    # Identifiers
    id = models.CharField(max_length=64, primary_key=True, default=generate_cht_id, editable=False)

    # Time
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    last_refreshed_at = models.DateTimeField(
        verbose_name="last refreshed at", null=True, blank=True
    )

    # State
    is_active = models.BooleanField(verbose_name="is active", default=True)

    # Domain
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    sql_query = models.TextField(
        verbose_name="SQL query", help_text="Read-only SELECT query that produces chart data"
    )
    chart_type = models.CharField(
        verbose_name="chart type", max_length=20, choices=CHART_TYPE_CHOICES, default="bar"
    )
    chart_spec = models.JSONField(
        verbose_name="chart spec",
        default=dict,
        blank=True,
        help_text="JSON chart specification: axes, colors, labels, options",
    )
    custom_d3_code = models.TextField(
        verbose_name="custom d3 code",
        blank=True,
        default="",
        help_text=(
            "Raw d3.js code for the chart. Receives 'data' (array of row objects), "
            "'container' (DOM element), and 'd3' (the d3 library) as arguments."
        ),
    )
    position = models.IntegerField(default=0, help_text="Ordering within dashboard grid")
    width = models.IntegerField(
        choices=WIDTH_CHOICES, default=6, help_text="CSS grid column span out of 12"
    )
    height = models.IntegerField(default=300, help_text="Chart height in pixels")
    cached_data = models.JSONField(
        verbose_name="cached data",
        default=dict,
        blank=True,
        help_text="Cached query results: {columns, rows, refreshed_at}",
    )
    last_error = models.TextField(verbose_name="last error", blank=True, default="")

    # Relations
    dashboard = models.ForeignKey(Dashboard, on_delete=models.CASCADE, related_name="charts")
    database = models.ForeignKey(
        DatabaseConnection, on_delete=models.PROTECT, related_name="charts"
    )

    def __str__(self) -> str:
        return f"{self.title} ({self.dashboard.name})"


class ChartGenerationLog(models.Model):
    """Audit log for AI dashboard/chart generation."""

    class Meta:
        verbose_name = "chart generation log"
        verbose_name_plural = "chart generation logs"
        ordering = ["-started_at"]

    STATUS_CHOICES: ClassVar[list[tuple[str, str]]] = [
        ("running", "Running"),
        ("success", "Success"),
        ("partial", "Partial"),
        ("failed", "Failed"),
    ]

    __prefix__: ClassVar[str] = "cgl"

    # Identifiers
    id = models.CharField(max_length=64, primary_key=True, default=generate_cgl_id, editable=False)

    # Time
    started_at = models.DateTimeField(auto_now_add=True)
    completed_at = models.DateTimeField(verbose_name="completed at", null=True, blank=True)

    # State
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="running")

    # Domain
    dashboard_name = models.CharField(verbose_name="dashboard name", max_length=200)
    execution_time_ms = models.IntegerField(verbose_name="execution time ms", null=True, blank=True)
    source_databases = models.JSONField(verbose_name="source databases", default=list, blank=True)
    source_docs = models.JSONField(verbose_name="source docs", default=list, blank=True)
    charts_created = models.IntegerField(verbose_name="charts created", null=True, blank=True)
    errors = models.JSONField(default=list, blank=True)
    error_message = models.TextField(verbose_name="error message", blank=True)
    prompt_used = models.TextField(verbose_name="prompt used", blank=True)
    agent_output = models.TextField(verbose_name="agent output", blank=True)

    # Relations
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    agent = models.ForeignKey(
        "AgentConfiguration", on_delete=models.SET_NULL, null=True, blank=True
    )

    def __str__(self) -> str:
        return f"{self.dashboard_name} — {self.status} ({self.started_at})"
