# Generated by Django 6.0.6 on 2026-06-10 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this agent configuration",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("codex", "Codex CLI"),
                            ("claude_code", "Claude Code CLI"),
                            ("codex_api", "Codex CLI (API key)"),
                            ("claude_code_api", "Claude Code CLI (API key)"),
                            ("openai_platform", "OpenAI Platform"),
                            ("claude_console", "Claude Console"),
                            ("openai_api", "OpenAI-compatible API (Custom)"),
                            ("ollama", "Local LLM with Ollama"),
                            ("openrouter", "OpenRouter (Gateway)"),
                        ],
                        default="codex",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Only one agent can be active at a time"
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        blank=True,
                        help_text="System prompt / AGENTS.md content sent to the AI agent",
                    ),
                ),
                (
                    "_auth_token",
                    models.TextField(
                        blank=True,
                        db_column="auth_token",
                        default="",
                        help_text="Encrypted auth.json content from ChatGPT subscription sign-in (device-code login)",
                    ),
                ),
                (
                    "_api_key",
                    models.TextField(
                        blank=True,
                        db_column="api_key",
                        default="",
                        help_text="Encrypted provider API key (e.g. OpenAI) for API-key CLI authentication",
                    ),
                ),
                (
                    "service_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Override for this agent's service URL (e.g. the Codex API gateway). Leave blank to fall back to the system-wide Codex Service URL or the CODEX_SERVICE_URL environment variable.",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Backend-specific settings. For direct API agents: `model`, `base_url`, and optional `max_tokens`.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Agent Configuration",
                "verbose_name_plural": "Agent Configurations",
                "ordering": ["-is_active", "name"],
            },
        ),
        migrations.CreateModel(
            name="Codebase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique identifier for this codebase", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Helps the AI agent understand what this repository contains",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("github", "GitHub")], default="github", max_length=20
                    ),
                ),
                (
                    "repo_url",
                    models.CharField(
                        help_text="e.g. https://github.com/owner/repo", max_length=500
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to use the repository's default branch",
                        max_length=255,
                    ),
                ),
                (
                    "subpath",
                    models.CharField(
                        blank=True,
                        help_text="Optional sub-directory to scope to, for monorepos (e.g. services/api)",
                        max_length=500,
                    ),
                ),
                (
                    "include_globs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Glob patterns to include, e.g. ["src/**", "*.py"]. Empty = everything (minus excludes).',
                    ),
                ),
                (
                    "exclude_globs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Glob patterns to exclude. Empty = a sensible default set (node_modules, build output, binaries).",
                    ),
                ),
                (
                    "_access_token",
                    models.CharField(
                        blank=True,
                        db_column="access_token",
                        help_text="Encrypted GitHub token. Leave blank for public repositories.",
                        max_length=500,
                    ),
                ),
                (
                    "default_branch",
                    models.CharField(blank=True, help_text="Resolved on sync", max_length=255),
                ),
                (
                    "cached_tree",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Cached repository file tree (list of {path, type, size}), refreshed on sync.",
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("syncing", "Syncing"),
                            ("ok", "Synced"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sync_error", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Codebase",
                "verbose_name_plural": "Codebases",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DatabaseConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique identifier for this connection",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Helps AI agent understand what data this database contains",
                    ),
                ),
                (
                    "engine",
                    models.CharField(
                        choices=[
                            ("postgresql", "PostgreSQL"),
                            ("mysql", "MySQL"),
                            ("mssql", "Microsoft SQL Server"),
                            ("oracle", "Oracle"),
                            ("sqlite", "SQLite"),
                            ("mariadb", "MariaDB"),
                            ("snowflake", "Snowflake"),
                            ("bigquery", "Google BigQuery"),
                            ("clickhouse", "ClickHouse"),
                        ],
                        default="postgresql",
                        max_length=50,
                    ),
                ),
                ("host", models.CharField(blank=True, max_length=255)),
                ("port", models.IntegerField(blank=True, null=True)),
                (
                    "database",
                    models.CharField(
                        blank=True,
                        help_text="Database name or file path for SQLite. Optional for engines with a default (e.g. ClickHouse uses 'default'), or when using a full connection_string.",
                        max_length=255,
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=255)),
                (
                    "_password",
                    models.CharField(
                        blank=True,
                        db_column="password",
                        help_text="Encrypted at rest",
                        max_length=500,
                    ),
                ),
                (
                    "connection_string",
                    models.TextField(
                        blank=True,
                        help_text="Optional: Full SQLAlchemy URL (overrides above fields)",
                    ),
                ),
                (
                    "extra_options",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional SQLAlchemy connect_args (e.g., SSL settings)",
                    ),
                ),
                (
                    "read_only",
                    models.BooleanField(
                        default=True,
                        help_text="Strongly recommended. Runs every query in a read-only database session on PostgreSQL, MySQL/MariaDB, SQLite, Oracle, and ClickHouse. SQL Server, BigQuery, and Snowflake cannot enforce this at the session level — use a read-only database user / IAM role there. All engines are additionally checked by the SQL validator.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Database Connection",
                "verbose_name_plural": "Database Connections",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DocumentationSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "folder_name",
                    models.CharField(
                        help_text="Folder name inside the documentations/ directory",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("database", "Database"),
                            ("codebase", "Codebase"),
                            ("manual", "Manual"),
                            ("policy", "Policy"),
                            ("api", "API"),
                            ("report", "Report"),
                            ("ontology", "Ontology"),
                            ("runbook", "Runbook"),
                        ],
                        default="database",
                        help_text="The category of documentation this source contains",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Helps AI understand what this source contains"
                    ),
                ),
                (
                    "file_patterns",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Glob patterns for files, e.g. ["*.md"] or ["*.py", "*.sql"]. Leave empty for default (*.md).',
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Documentation Source",
                "verbose_name_plural": "Documentation Sources",
                "ordering": ["folder_name"],
            },
        ),
        migrations.CreateModel(
            name="MCPServerConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this MCP server", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="What this MCP server provides"),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        help_text="Full MCP endpoint URL, e.g. https://example.com/mcp (leave blank for the built-in server)",
                        max_length=500,
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        blank=True, help_text="Deprecated — use `url` instead", max_length=255
                    ),
                ),
                (
                    "port",
                    models.IntegerField(
                        blank=True, help_text="Deprecated — use `url` instead", null=True
                    ),
                ),
                (
                    "transport",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Local (built-in)"),
                            ("sse", "SSE"),
                            ("streamable-http", "Streamable HTTP"),
                        ],
                        default="",
                        help_text="Transport protocol (leave blank for the built-in server)",
                        max_length=20,
                    ),
                ),
                (
                    "_auth_token",
                    models.CharField(
                        blank=True,
                        db_column="auth_token",
                        help_text="Encrypted bearer token sent as Authorization: Bearer …",
                        max_length=500,
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Extra HTTP headers sent to the MCP server, e.g. {"X-API-Key": "abc"}',
                    ),
                ),
                (
                    "command",
                    models.CharField(
                        blank=True,
                        help_text='Executable to run, e.g. "npx" or "uvx". Set this for local subprocess servers.',
                        max_length=500,
                    ),
                ),
                (
                    "args",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Arguments for the command, e.g. ["-y", "@notionhq/notion-mcp-server"]',
                    ),
                ),
                (
                    "_command_env",
                    models.TextField(
                        blank=True,
                        db_column="command_env",
                        help_text="Encrypted JSON dict of environment variables passed to the subprocess.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_builtin",
                    models.BooleanField(
                        default=False, help_text="Built-in servers cannot be edited or deleted"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "MCP Server",
                "verbose_name_plural": "MCP Servers",
                "ordering": ["-is_builtin", "name"],
            },
        ),
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.TextField()),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("boolean", "Boolean"),
                            ("json", "JSON"),
                        ],
                        default="string",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Explain what this setting does"),
                ),
            ],
            options={
                "verbose_name": "System Configuration",
                "verbose_name_plural": "System Configuration",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="ChartGenerationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("dashboard_name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("execution_time_ms", models.IntegerField(blank=True, null=True)),
                ("source_databases", models.JSONField(blank=True, default=list)),
                ("source_docs", models.JSONField(blank=True, default=list)),
                ("charts_created", models.IntegerField(blank=True, null=True)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("error_message", models.TextField(blank=True)),
                ("prompt_used", models.TextField(blank=True)),
                ("agent_output", models.TextField(blank=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.agentconfiguration",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chart Generation Log",
                "verbose_name_plural": "Chart Generation Logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "tools_used",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of MCP tool names used in this assistant message",
                    ),
                ),
                (
                    "sources_used",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of {uri, name} dicts for MCP sources attached to this user message",
                    ),
                ),
                (
                    "prompts_used",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of {name, display_name} dicts for prompts attached to this user message",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.chatsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "auto_refresh",
                    models.BooleanField(
                        default=False, help_text="Automatically refresh chart data on a schedule"
                    ),
                ),
                (
                    "refresh_interval",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("5", "Every 5 minutes"),
                            ("15", "Every 15 minutes"),
                            ("30", "Every 30 minutes"),
                            ("60", "Every hour"),
                            ("360", "Every 6 hours"),
                            ("720", "Every 12 hours"),
                            ("1440", "Every 24 hours"),
                        ],
                        help_text="How often to refresh chart data",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard",
                "verbose_name_plural": "Dashboards",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Chart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "sql_query",
                    models.TextField(help_text="Read-only SELECT query that produces chart data"),
                ),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("bar", "Bar"),
                            ("line", "Line"),
                            ("scatter", "Scatter"),
                            ("pie", "Pie"),
                            ("area", "Area"),
                            ("grouped_bar", "Grouped Bar"),
                            ("stacked_bar", "Stacked Bar"),
                            ("heatmap", "Heatmap"),
                            ("custom", "Custom d3.js"),
                        ],
                        default="bar",
                        max_length=20,
                    ),
                ),
                (
                    "chart_spec",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON chart specification: axes, colors, labels, options",
                    ),
                ),
                (
                    "custom_d3_code",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Raw d3.js code for the chart. Receives 'data' (array of row objects), 'container' (DOM element), and 'd3' (the d3 library) as arguments.",
                    ),
                ),
                (
                    "position",
                    models.IntegerField(default=0, help_text="Ordering within dashboard grid"),
                ),
                (
                    "width",
                    models.IntegerField(
                        choices=[
                            (3, "Quarter"),
                            (4, "Third"),
                            (6, "Half"),
                            (8, "Two-thirds"),
                            (12, "Full"),
                        ],
                        default=6,
                        help_text="CSS grid column span out of 12",
                    ),
                ),
                ("height", models.IntegerField(default=300, help_text="Chart height in pixels")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "cached_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Cached query results: {columns, rows, refreshed_at}",
                    ),
                ),
                ("last_refreshed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charts",
                        to="core.dashboard",
                    ),
                ),
                (
                    "database",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charts",
                        to="core.databaseconnection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chart",
                "verbose_name_plural": "Charts",
                "ordering": ["position", "title"],
            },
        ),
        migrations.CreateModel(
            name="DocGenerationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("destination", models.CharField(max_length=500)),
                ("filename", models.CharField(blank=True, max_length=255)),
                ("doc_type", models.CharField(max_length=50)),
                (
                    "is_library",
                    models.BooleanField(
                        default=False,
                        help_text="True when this run generated a multi-file documentation library (a folder tree) rather than a single file.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("execution_time_ms", models.IntegerField(blank=True, null=True)),
                ("source_databases", models.JSONField(blank=True, default=list)),
                ("source_docs", models.JSONField(blank=True, default=list)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("error_message", models.TextField(blank=True)),
                ("file_size", models.IntegerField(blank=True, null=True)),
                ("prompt_used", models.TextField(blank=True)),
                ("agent_output", models.TextField(blank=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.agentconfiguration",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Doc Generation Log",
                "verbose_name_plural": "Doc Generation Logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="PromptConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "prompt_name",
                    models.CharField(
                        help_text="Internal prompt name (e.g., 'analyze_table')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name shown in autocomplete", max_length=100
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "content",
                    models.TextField(
                        default="",
                        help_text="The prompt instructions. This text is prepended to the user's message as context for the AI agent.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mcp_server",
                    models.ForeignKey(
                        help_text="MCP server this prompt belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompts",
                        to="core.mcpserverconfiguration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prompt Configuration",
                "verbose_name_plural": "Prompt Configurations",
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="QueryAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("query", models.TextField()),
                ("row_count", models.IntegerField(null=True)),
                ("execution_time_ms", models.IntegerField(null=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "database",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.databaseconnection",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Query Audit Log",
                "verbose_name_plural": "Query Audit Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("sql_query", models.TextField(help_text="Read-only SELECT or WITH query")),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("interval", "Every N Minutes/Hours"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "schedule_interval_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="Run every N minutes (for interval schedule)",
                        null=True,
                    ),
                ),
                (
                    "schedule_time",
                    models.TimeField(
                        blank=True, help_text="Time of day for scheduled runs", null=True
                    ),
                ),
                (
                    "schedule_day_of_week",
                    models.IntegerField(
                        blank=True, help_text="0=Monday .. 6=Sunday (for weekly)", null=True
                    ),
                ),
                (
                    "schedule_day_of_month",
                    models.IntegerField(blank=True, help_text="1-28 (for monthly)", null=True),
                ),
                (
                    "next_run_at",
                    models.DateTimeField(
                        blank=True, help_text="Computed next execution time", null=True
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("in_app", "In-App"),
                            ("email", "Email"),
                            ("slack", "Slack"),
                            ("teams", "Microsoft Teams"),
                        ],
                        default="in_app",
                        max_length=20,
                    ),
                ),
                (
                    "delivery_config",
                    models.JSONField(
                        blank=True, default=dict, help_text="Future: email addresses, webhook URLs"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "database",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="core.databaseconnection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Definition",
                "verbose_name_plural": "Report Definitions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReportExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("execution_time_ms", models.IntegerField(blank=True, null=True)),
                ("row_count", models.IntegerField(blank=True, null=True)),
                ("result_file_path", models.CharField(blank=True, default="", max_length=255)),
                ("error_message", models.TextField(blank=True)),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="core.reportdefinition",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Execution",
                "verbose_name_plural": "Report Executions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "max_row_limit",
                    models.IntegerField(default=100, help_text="Maximum rows per query"),
                ),
                ("can_manage_users", models.BooleanField(default=False)),
                (
                    "can_chat",
                    models.BooleanField(
                        default=True,
                        help_text="Allow users with this role to use the chat interface.",
                    ),
                ),
                (
                    "can_view_tethers",
                    models.BooleanField(
                        default=True, help_text="Allow users with this role to view Tethers."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_admin_role",
                    models.BooleanField(
                        default=False,
                        help_text="Admin roles bypass all access restrictions. Access control settings are ignored.",
                    ),
                ),
                (
                    "allowed_codebases",
                    models.ManyToManyField(blank=True, related_name="roles", to="core.codebase"),
                ),
                (
                    "allowed_databases",
                    models.ManyToManyField(
                        blank=True, related_name="roles", to="core.databaseconnection"
                    ),
                ),
                (
                    "allowed_doc_sources",
                    models.ManyToManyField(
                        blank=True, related_name="roles_docs", to="core.documentationsource"
                    ),
                ),
                (
                    "allowed_mcp_servers",
                    models.ManyToManyField(
                        blank=True, related_name="roles", to="core.mcpserverconfiguration"
                    ),
                ),
                (
                    "allowed_prompts",
                    models.ManyToManyField(
                        blank=True, related_name="roles", to="core.promptconfiguration"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="reportdefinition",
            name="allowed_roles",
            field=models.ManyToManyField(
                blank=True, related_name="allowed_reports", to="core.role"
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="allowed_roles",
            field=models.ManyToManyField(
                blank=True, related_name="allowed_dashboards", to="core.role"
            ),
        ),
        migrations.CreateModel(
            name="Tether",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allowed_roles",
                    models.ManyToManyField(
                        blank=True, related_name="allowed_tethers", to="core.role"
                    ),
                ),
                (
                    "codebase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tethers",
                        to="core.codebase",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tethers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "database_doc_source",
                    models.ForeignKey(
                        limit_choices_to={"doc_type": "database"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tethers_as_database",
                        to="core.documentationsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tether",
                "verbose_name_plural": "Tethers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TetherVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version_number", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("execution_time_ms", models.IntegerField(blank=True, null=True)),
                ("graph_json", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                (
                    "agent_log_excerpt",
                    models.TextField(
                        blank=True, help_text="Last ~4kB of Codex stream for debugging"
                    ),
                ),
                ("prompt_used", models.TextField(blank=True)),
                (
                    "tether",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="core.tether",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tether Version",
                "verbose_name_plural": "Tether Versions",
                "ordering": ["-version_number"],
                "unique_together": {("tether", "version_number")},
            },
        ),
        migrations.AddField(
            model_name="tether",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                help_text="Latest successful run; what the viewer renders.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.tetherversion",
            ),
        ),
        migrations.CreateModel(
            name="ToolConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tool_name",
                    models.CharField(
                        help_text="Internal tool name (e.g., 'search_docs')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(help_text="Human-readable name", max_length=100)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("querying", "Querying"),
                            ("docs", "Docs"),
                            ("charts", "Charts"),
                            ("codebases", "Codebases"),
                            ("tethers", "Tethers"),
                            ("reports", "Reports"),
                        ],
                        default="",
                        help_text="TetherDust feature this tool belongs to (groups tools in the console).",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="AI-facing description that guides when/how the tool is used"
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "input_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='MCP tool input schema (JSON Schema). Example: {"type": "object", "properties": {"query": {"type": "string"}}, "required": ["query"]}',
                    ),
                ),
                (
                    "source_code",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Python handler code. Must define an async function handle(arguments: dict) -> str that returns the tool result text.",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Tool-specific settings (e.g., max_results, timeout)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mcp_server",
                    models.ForeignKey(
                        help_text="MCP server this tool belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tools",
                        to="core.mcpserverconfiguration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tool Configuration",
                "verbose_name_plural": "Tool Configurations",
                "ordering": ["category", "display_name"],
            },
        ),
        migrations.AddField(
            model_name="role",
            name="allowed_tools",
            field=models.ManyToManyField(
                blank=True, related_name="roles", to="core.toolconfiguration"
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.role",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
